# Generated by Django 2.1.2 on 2018-11-16 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_from_supplying_hospital', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='InterClinicDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('location_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_a', to='project.ClinicLocation')),
                ('location_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_b', to='project.ClinicLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('QUEUED_FOR_PROCESSING', 'Queued for Processing'), ('PROCESSING_BY_WAREHOUSE', 'Processing by Warehouse'), ('QUEUED_FOR_DISPATCH', 'Queued for Dispatch'), ('DISPATCHED', 'Dispatched')], default='QUEUED_FOR_PROCESSING', max_length=200)),
                ('priority', models.CharField(choices=[('1', 'High'), ('0', 'Medium'), ('-1', 'Low')], default=-1, max_length=200)),
                ('dateOrdered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dateProcessed', models.DateTimeField(blank=True, null=True)),
                ('dateDispatched', models.DateTimeField(blank=True, null=True)),
                ('dateDelivered', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Item')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Order')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('CLINIC_MANAGER', 'Clinic Manager'), ('WAREHOUSE_PERSONNEL', 'Warehouse Personnel'), ('DISPATCHER', 'Dispatcher')], default='CLINIC_MANAGER', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='project.OrderedItem', to='project.Item'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordering_clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ClinicLocation'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplying_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.HospitalLocation'),
        ),
        migrations.AddField(
            model_name='cliniclocation',
            name='supplying_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.HospitalLocation'),
        ),
    ]
