# Generated by Django 2.1.2 on 2018-11-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20181117_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pet_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
