# Generated by Django 2.1.2 on 2018-11-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20181101_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', max_length=200),
        ),
    ]
