# Generated by Django 2.1.2 on 2018-11-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_user_pet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pet_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
