# Generated by Django 2.1.2 on 2018-11-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20181117_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CM'), (2, 'WP'), (3, 'DI'), (4, 'AD')], null=True),
        ),
    ]
